### ISSUE TITLE
Suggestion: Allow for multiple commands

### ISSUE THREAD

**Issue by Alxandr** [madskristensen/OpenCommandLine#1]
It would be really awesome if I could register more than one command. So that I could right click and select `Open in PowerShell` or `Open in Git Bash`. With customization names and executables. Don't really need keyboard shortcut for each of them, could be a primary one with the alt+space shortcut, but just having them in the project/solution context menu would be really helpful :)

**Comment by kfrancis** [comment]
+1 This would allow the VS Developer Console to be added.

**Comment by carloscds** [comment]
+1
