### ISSUE TITLE
Default key binding conflicts with Windows control menu

### ISSUE THREAD

**Issue by breyed** [madskristensen/OpenCommandLine#11]
<kbd>Alt+Space</kbd> is the Windows-wide keyboard shortcut to open a desktop application's control menu. (For those who remember back to the Windows 3.x days, before Windows 95 put an icon in the title bar, a wide bar (a space bar) was shown in the upper left as a mnemonic. MDI windows showed a short bar (a hyphen), since their control menu shortcut was <kbd>Alt+Hyphen</kbd> ([screenshot](http://en.wikipedia.org/wiki/Windows_3.0#mediaviewer/File:Windows_3.0_workspace.png)).)

Keyboard access to the control menu is useful for quickly minimizing and maximizing an application. It's even handy for closing an application, since <kbd>Alt+Space,C</kbd> is a tad easier than stretching the left hand up to <kbd>Alt+F4</kbd>.

A better default would be <kbd>Alt+`</kbd>. Besides not conflicting with anything, it would make the open-command-line feature more [Quake-like](http://www.hanselman.com/blog/QuakeModeConsoleForVisualStudioOpenACommandPromptWithAHotkey.aspx).

**Comment by madskristensen** [comment]
I'm aware that Alt+Space is conflicting with other shortcuts. That's why you can change the shortcut in Tools -> Options.

I decided to go with Alt+Space anyway, because there is nothing in that menu that can't be done smarter with the Win key. Example:

Restore window: Win+Down
Minimize window: Win+Down, Win+Down
Maximize window: Win+Up
Close app: Alt+F4

**Comment by breyed** [comment]
I considered the Windows key variants. Indeed the Maximize and Restore commands have direct equivalents. Minimize isn't quite the same. For example, if Visual Studio has been docked left (via Win+Left), if you minimize it with Win+Down,Win+Down, when you later restore the window, it restores to its undocked state, whereas if you minimize it with Alt+Space,N, it restores docked.

It's a subtle difference. It's not like it's difficult to re-dock the window. Perhaps it's just hard letting go of a keyboard shortcut I've been using for 25 years. :-)

**Comment by monoblaine** [comment]
By default, making the shortcut work only when the Solution Explorer is focused (The `Use new shortcut in` option) might be a better choice. It is globally defined out-of-the-box but it doesn't need to be so, I think.
