### ISSUE TITLE
In 1.6.98 Changes to Command Line Options Don't Stick

### ISSUE THREAD

**Issue by richardcox13** [madskristensen/OpenCommandLine#12]
Having just updated, I wanted to remove the execution policy bypass setting (my PSH environment is set up for remote signed).

But editing the command arguments setting (leaving just "-NoExit"), closing options dialog with OK and then re-opening and the change I've just made is lost.

I then tried the custom preset, put PowerShell.exe in the command (and left the arguments blank), on re-opening options the command was now cmd.exe.

It appears the defaults from the preset are always overriding the other settings (and there is no ability to select no preset).

**Comment by madskristensen** [comment]
Fix is coming. Should be there in less than an hour. Thanks for the heads up on this

**Comment by madskristensen** [comment]
version 1.6.99 has just been released with the fix

**Comment by richardcox13** [comment]
Thanks, much better!
