### ISSUE TITLE
Receive "Value Cannot Be Null. Parameter name: name" error message when attempting to launch cmd.exe

### ISSUE THREAD

**Issue by jbarker4682** [madskristensen/OpenCommandLine#14]
I am able to launch the Developer Command Prompt and Powershell, but when I try to launch the basic cmd.exe, I get the above Visual Studio error dialog.

**Comment by TaylorBarrick** [comment]
Within Tools->Options, Environment->Command Line, you can either turn on the 'Always open at solution level' or add %1 to the Command Arguments.

The first obviously opens at the Solution level, but the Command Argument option opens at the project level of your currently open editor tab.

**Comment by jbarker4682** [comment]
Hey Taylor, thanks for the input.  That fixes the error message, but the resulting command window defaults to C:\Windows instead of my project folder.  It looks like there might be an issue with the fact that I'm running VS from within Parallels on a Mac, and it doesn't like the UNC paths being used under the hood:

'\\psf\Home\Documents\Visual Studio 2013\Projects\Foo\'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.

Any ideas if there is a workaround for this?

**Comment by bgever** [comment]
It looks more obscure than that. The same issue is happening for me since yesterday when I started using a Mac keyboard with a Surface Pro 3 (Win 8.1). It's the keyboard combination of Alt+Space, on the Mac keyboard, because it works fine on the Touch Cover. Oddly, on my Mac with Parallels I haven't encountered this problem before.

Since this issue is so hard to reproduce, is there some way I can help debugging the key handling code?

**Comment by bgever** [comment]
Interestingly, after opening the console with Alt+Space on the Type Cover keyboard, now the Mac keyboard works as expected. I'm currently unable to reproduce the error.

**Comment by TaylorBarrick** [comment]
jbarker4682, the UNC path is a bit of a problem for cmd.exe.  I tried doing something with the [pushd command](https://technet.microsoft.com/en-us/library/bb490978.aspx) and [usage](http://www.intelliadmin.com/index.php/2007/02/simplify-unc-usage-in-command-line-batch-files/), it seems like it could work if you build a batch file that does something like this:

   *pushd %1*
   *cmd.exe*
   *popd*

Then change your command from cmd.exe to the name of the batch file and the command argument to %1 to pass the UNC working directory.

**Comment by someuser77** [comment]
I had the same issue.
Adding %1 like @TaylorBarrick suggested fixed that for me but perhaps this should be already in the preset?
For some reason the out-of-the-box setup doesn't work and the additional step is required.
By out-of-the-box I mean: Install -> Restart VS -> Open some project -> Press Alt + Space
Great work other than that, thank you for writing this addon!

**Comment by madskristensen** [comment]
Is there a way I could make this one of the presets without having the batch file? Or more explicitly asked, can this be done solely by adding the right strings to `Command` and `Command Arguments` in the Tools | Options page?

**Comment by jbarker4682** [comment]
Hey guys, thanks for the help. Unfortunately, I was not able to get this to work. I created a cmd.bat file and added the lines above:

pushd %1
cmd.exe
popd

I then changed the settings to point to cmd.bat passing %1 as the command argument, but I get the following output in the command window:

'\\psf\home\Documents\Visual Studio 2013\Projects\Foo\'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.

C:\Windows>pushd %1
The system cannot find the path specified.

C:\Windows>cmd.exe
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows>

**Comment by TaylorBarrick** [comment]
@jbarker4682, it seems that the %1 is just not getting expanded in this scenario.  Environment.ExpandEnvironmentVariables needs an environment variable rather that a number parameter.  Not sure if this could be accomplished without either adding some custom parameters to access DTE fields like dte.Solution.FullName.

Hi @madskristensen, I think cmd.exe is the blocking element here, so no combination of flags (that I have found) will enable the unc path.  It might be necessary to do something like you are doing for the dev command prompt batch file, if the unc path is detected.

**Comment by madskristensen** [comment]
The extension can call a batch file that we can ship along with the extension. That sounds like it's the only solution. There is code in right now that will expand `%folder%` with the current folder (solution, project or project folder), but it hasn't been released yet.

**Comment by TaylorBarrick** [comment]
Sure thing!

**Comment by madskristensen** [comment]
Fixed the null reference exception

**Comment by jbarker4682** [comment]
Thanks guys!

**Comment by bgever** [comment]
Thanks indeed. :-)
