### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by Bobdina** [madskristensen/OpenCommandLine#16]
I had a nullreferenceexception while using this extension for a while on this line here:

`var arguments = options.Arguments.Replace("%folder%", folder);`
(method OpenCustom, OpenCommandLinePackage)

The options.Arguments string was `null`. I assume this is because I had an old version of opencommandline and later I installed a newer version. I solved it by setting the arguments in the options panel, and then unsetting them.
Maybe this could be checked for null to accommodate older versions?

**Comment by brgrz** [comment]
I get a dialog window saying "Object reference not set to an instance of an object." when trying to open the cmd prompt.

It works for Developer command prompt and Powershell.

**Comment by Bobdina** [comment]
@brgrz : That does sound similar. Did you try changing the "Command arguments" option in the visual studio options, to see if that helps like it did for me?

**Comment by madskristensen** [comment]
I'm working on a fix right now. I'll release an update shortly
