### ISSUE TITLE
Error when starting Visual Studio: Assembly Microsoft.VisualStudio.Shell.12.0 missing

### ISSUE THREAD

**Issue by daredude** [madskristensen/OpenCommandLine#2]
When opening a solution in Visual Studio I get an error dialog, that tells me the `OpenCommandLinePackage` can not be loaded. 
In the `ActivityLog.xml` I can see this entry:

```xml
<entry>
    <record>469</record>
    <time>2015/01/21 10:23:48.282</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [OpenCommandLinePackage]</description>
    <guid>{F4AB1E64-5D35-4F06-BAD9-BF414F4B3BBB}</guid>
    <hr>80070002</hr>
    <errorinfo>Die Datei oder Assembly "Microsoft.VisualStudio.Shell.12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.</errorinfo>
</entry>
```

The `errorinfo` is in german language and means `File or Assembly "Microsoft.VisualStudio.Shell.12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" missing.`

**Comment by nsleigh** [comment]
Same problem here. I looks like it won't install unless you have VS2013 installed.

**Comment by madskristensen** [comment]
Are you using VS2012?

**Comment by daredude** [comment]
Yes, VS2012 on Win8.1 64bit

**Comment by madskristensen** [comment]
This should now be fixed in version 1.3 which I just released

**Comment by daredude** [comment]
Awesome, it's working fine. Great job!

**Comment by madskristensen** [comment]
Sweet. Thanks for reporting this
