### ISSUE TITLE
cmder not opening in current directory

### ISSUE THREAD

**Issue by delebash** [madskristensen/OpenCommandLine#23]
Windows 7 x64
Visual Studio Community 2015

When using cmder with the option /START %folder% cmder opens but not in the current directory, it says not a valid directory

I can test by changing the option to /START C:\ and it does open in C:\ so I think there is something wrong with the %folder% variable 

Thanks.

**Comment by madskristensen** [comment]
I've made a fix to surround `%folder%` with quotes so it works with paths containing spaces. You can unblock yourself by using this as the argument:

```
/START "%folder%"
```

**Comment by delebash** [comment]
works great, thanks I should have thought of that :)

**Comment by andresvillenas** [comment]
Hi, I tried using the parameters /START "%folder%" but it didn't work in VS2017
