### ISSUE TITLE
Always open at the project level

### ISSUE THREAD

**Issue by xt0rted** [madskristensen/OpenCommandLine#24]
Any time I open a console it's to work with tools such as `npm`, `bower`, `gulp`, `tsd`, `git`, `hg`, etc. which need to run in the project folder or solution folder. Would it be possible to add a setting so if you're in a project the console always opens in the project folder, but if you're on the solution or a non project file then it opens at the solution level? I don't think I've ever opened a console to do anything in a project's sub folders, it's always the solution or project folder I'm concerned about.

**Comment by madskristensen** [comment]
That's a great idea.

**Comment by madskristensen** [comment]
What about this:

1. If you right-click in Solution Explorer, console opens at the directory you clicked (folder, proj or sol)
2. When hitting `CTRL+SPACE` in the editor on an open document, it opens a console on the project

Basically, the Solution Explorer right-click behavior stays the same. If a document is active and you hit `CTRL+SPACE` then it opens on the solution level instead of the location of that document.

Makes sense?

**Comment by drub0y** [comment]
As long as solution level still works I agree with this. Could just be an option you configure in settings too.

**Comment by dpen2000** [comment]
> When hitting CTRL+SPACE in the editor on an open document, it opens a console on the project
Shouldn't it open the console in the location of that file in this case? It may be a sub-directory of the project.

**Comment by madskristensen** [comment]
@drub0y, good point. I just added that to my comment

**Comment by madskristensen** [comment]
@dpen2000, I just added a comment that this should be something you can opt in to in the settings

**Comment by madskristensen** [comment]
Here is what that setting could look like:

![screenshot_1](https://cloud.githubusercontent.com/assets/1258877/10091788/5f5f2358-62f4-11e5-98ca-7929d0e25487.png)

I think the **Open files at project level** is a little unclear. Any ideas for improvement?

**Comment by david-driscoll** [comment]
I would tend to agree, I've almost never needed a sub folder, solution level sometimes, but its easy enough to cd up one directory if needed.

**Comment by IDisposable** [comment]
+1 on project (or SLN) level as appropriate. Now can we make it easier for the prompt to be posh-git instead of cmd? ;)

**Comment by madskristensen** [comment]
@IDisposable, you can set the default to be post-git in the settings

**Comment by madskristensen** [comment]
You can test out this new setting in the latest CI build http://vsixgallery.com/extension/f4ab1e64-5d35-4f06-bad9-bf414f4b3bbb/

**Comment by xt0rted** [comment]
So far it's working good.

**Comment by hakenr** [comment]
"Open prompt in project root directory"?
