### ISSUE TITLE
Open files at project level has inconsistent behavior

### ISSUE THREAD

**Issue by xt0rted** [madskristensen/OpenCommandLine#28]
If I have a file open from in a sub folder and use `Alt + space` to open a command line then it opens at the project level.

If I select a file or folder in the solution explorer and use `Alt + space` to open a command line then it opens at the folder that's selected, not the project level.

If I use the context menu then the command line always opens to the folder which is correct, but using `Alt + space` I thought it was always supposed to open at the project level.

**Comment by madskristensen** [comment]
`Alt+Space` invokes the same command as when you right-click a folder in Solution Explorer. The difference in behavior has to do with what window in Visual Studio that's active. 

If the editor is active when the command is invoked, it opens on the project level. 
If the Solution Explorer is active when the command is invoked, it opens on the selected folder level.

I'm a little confused by this myself sometimes. Do you think it should always open at the project level no matter what you selected in Solution Explorer?
