### ISSUE TITLE
Extension keeps disabling on restart

### ISSUE THREAD

**Issue by remcoros** [madskristensen/OpenCommandLine#30]
I noticed this with all extensions from Mads (I use open command line,  web compiler and web essentials).

Everytime I start Visual Studio, those extensions are disabled.

The only way to enable them is to click 'enable' from extension manager, then restart visual studio.

In that new instance, the extensions are enabled, but as soon as I start a new instance (or restart), those three extensions are disabled again.

The only thing I found is that this only happens with these three extensions.

I noticed this on the package class:
[ProvideAutoLoad(UIContextGuids80.SolutionExists)]

I have no experience with VS SDK, but it looks like this means the extension will only be enabled when a solution is loaded.

The solution is loaded though, so it might actually be a bug in VS 2015 maybe?

If you need more info / logs, let me know.

**Comment by madskristensen** [comment]
It's likely an error in the automatic update feature that will corrupt the MEF cache. Try this https://visualstudiogallery.msdn.microsoft.com/22b94661-70c7-4a93-9ca3-8b6dd45f47cd

**Comment by remcoros** [comment]
That didn't seem to help.

Are there any log/trace files I could look into?

**Comment by remcoros** [comment]
I backed up my settings, removed those three extensions and ran devenv /resetusersettings and /resetsettings. Imported settings and reinstalled the extensions again.

Looks like the problem is gone.
