### ISSUE TITLE
Extension fails to load on VS2013

### ISSUE THREAD

**Issue by tomascassidy** [madskristensen/OpenCommandLine#36]
Just upgraded to the latest version 2.1.171 and now an error is thrown on opening Visual Studio saying the package did not load correctly.

Could it be an identical issue to https://github.com/madskristensen/FileNesting/issues/56?

**Comment by madskristensen** [comment]
Thanks for reporting this. Yes, it was the same issue. It should be fixed now. Can I get you to verify by trying out the latest [CI build](http://vsixgallery.com/extension/f4ab1e64-5d35-4f06-bad9-bf414f4b3bbb/)?

**Comment by alexmajor** [comment]
I can confirm version 2.1.173 fixed error message in Windows 7 with Visual Studio 2013.
![devenv_2016-06-02_11-36-42](https://cloud.githubusercontent.com/assets/5017286/15750962/5560c536-28b6-11e6-95aa-f214ee9c0c98.png)
