### ISSUE TITLE
Syntax highlighting issue with quotes

### ISSUE THREAD

**Issue by gregcooper10** [madskristensen/OpenCommandLine#37]
I noticed that the syntax highlighting on command lines (.bat) is isn't quite right when using double or single quotes around arguments. All text between the first quote in the line and the last quote in the line is highlighted as a string, rather that from one quote to the next.

E.G.

`test.exe -table "t name" -database "dbase1" -output "output 1.txt" -input no-quote.txt`

In the above:

`-table` is highlighted correctly
`"t name" -database "dbase1" -output "output 1.txt"` is all highlighted as text
`-input no-quote.txt` is highlighted correctly

I am using Visual Studio 2015 Version 14.0.25123.00 Update 2 on Windows 7 Professional.

Apart from that it's great :)

Kind Regards,

Greg

**Comment by madskristensen** [comment]
Thanks for the bug report. The issue has been fixed and an update released to the VS Gallery
