### ISSUE TITLE
Extension is always disabled on opening VS2015 ENT

### ISSUE THREAD

**Issue by sitefinitysteve** [madskristensen/OpenCommandLine#41]
I love this extension, but it's driving me nuts that I have to keep re-enabling it

Any thoughts as to why it's always disabled on VS load?  Means I need to launch VS->enable->relaunch everytime.
![image](https://cloud.githubusercontent.com/assets/1542376/17972826/2500738e-6aae-11e6-82b5-7ca3494c665e.png)

**Comment by madskristensen** [comment]
This is an issue with Visual Studio. They claim to have fixed parts of it in Update 3. You can always try this https://visualstudiogallery.msdn.microsoft.com/22b94661-70c7-4a93-9ca3-8b6dd45f47cd

Closing here since it's a VS issue and not something that can be fixed by an individual extension

**Comment by sitefinitysteve** [comment]
Fair enough if it's not your issue... I have been on Update3 for a while though, I will note it over there thx
