### ISSUE TITLE
Add an option for Bash on Ubuntu on Windows shell

### ISSUE THREAD

**Issue by Neme12** [madskristensen/OpenCommandLine#43]
It would be really useful to open the new Windows Subsystem for Linux bash shell from the current folder.

**Comment by prayush09m** [comment]
I am also having the same issue here. Will be really appreciative if I can get this working

**Comment by arbolbinario** [comment]
I was able to get this working by using the following configuration:

![Command Line Settings](https://cloud.githubusercontent.com/assets/16406635/22709219/0a53ca1a-ed47-11e6-9e59-cd041a389f65.png)
