### ISSUE TITLE
Command line not referencing external Web Tools path.

### ISSUE THREAD

**Issue by aaronjones** [madskristensen/OpenCommandLine#44]
If you update node & npm externally and subsequently update:
 "Tools > Options -> Projects and Solutions > External Web Tools" 
and make the new version of node accessible to Visual Studio there is an issue. 
When starting the commandline from this tool and executing "npm -v" you can see you are still stuck on Visual Studio's older version of npm (2.14.21).   Presumably the path from External Web Tools is not leveraged.

![externalwebtoolsscreenshot](https://cloud.githubusercontent.com/assets/898710/20733651/2ede6b3e-b65a-11e6-89c4-f4c9a75481b4.png)
![npmfromcommandlinetool](https://cloud.githubusercontent.com/assets/898710/20733653/2ee2b4b4-b65a-11e6-95e4-515cb2a47f55.png)
![npmfromwindowscommandline](https://cloud.githubusercontent.com/assets/898710/20733652/2ee011b4-b65a-11e6-8d94-b658bcf617f2.png)

**Comment by madskristensen** [comment]
Fixed
