### ISSUE TITLE
Support environment variables in arguments

### ISSUE THREAD

**Issue by smourier** [madskristensen/OpenCommandLine#55]
Hi,

I really like the tool :-) Could it be possible to add support for some variables (beyond %folder%)? To be able to do something like this, i.e. vary the command arguments depending on my build configuration (Debug/Release), for example:

![commandlinevariables](https://cloud.githubusercontent.com/assets/5328574/26687941/895e4d18-46f1-11e7-888f-36d53adad1bf.png)

I could try to do it myself if you accept pull requests.

**Comment by madskristensen** [comment]
I definitely take PRs and this is a great idea!

**Comment by nhammadi** [comment]
@madskristensen this issue should be closed now since @smourier fix #56
