### ISSUE TITLE
Addon broken with latest VS update?

### ISSUE THREAD

**Issue by onedevteam** [madskristensen/OpenCommandLine#71]
Yesterday, i have updated VS to latest 15.8.0 version.

After that update, looks like your addon stopped working?
installed version of addon is 2.3 from 14.08.2018

![image](https://user-images.githubusercontent.com/7267540/44210168-0eb0bd00-a166-11e8-9568-9bf2654c1369.png)

**Comment by treg** [comment]
same issue...

**Comment by onedevteam** [comment]
After update to 15.8.3 option started to work again...
