### ISSUE TITLE
Add preset for Windows terminal

### ISSUE THREAD

**Issue by iAmBipinPaul** [madskristensen/OpenCommandLine#77]

**Comment by IanKemp** [comment]
Would be a bit useless ATM since Terminal currently doesn't support any command-line options, so you can't pass e.g. the current solution directory to it.

**Comment by kapsiR** [comment]
There is a workaround for that.
[The solution from Rick Strahl](https://weblog.west-wind.com/posts/2019/Sep/03/Programmatically-Opening-Windows-Terminal-in-a-Specific-Folder):
- You can customize the startup default Terminal Shell Profile
   Set `"startingDirectory" : "%__CD__%"`
 - Side effect: Windows shortcut launching launches from System folder

**Comment by IanKemp** [comment]
> There is a workaround for that.
> [The solution from Rick Strahl](https://weblog.west-wind.com/posts/2019/Sep/03/Programmatically-Opening-Windows-Terminal-in-a-Specific-Folder):
> 
> * You can customize the startup default Terminal Shell Profile
>   Set `"startingDirectory" : "%__CD__%"`
> * Side effect: Windows shortcut launching launches from System folder

Since the latest release of WT you can accomplish this with `"startingDirectory" : "."` which is a little less verbose :)

**Comment by RehanSaeed** [comment]
Windows Terminal now supports setting the starting directory

```bash
wt -d C:\Users\cinnamon\GitHub\WindowsTerminal
```

I'd also like Windows Terminal to be the default selection if available on the system. Can't wait for this issue to be resolved.

https://devblogs.microsoft.com/commandline/windows-terminal-preview-v0-9-release/

**Comment by KZeronimo** [comment]
@RehanSaeed  - agreed - selecting open at solution level or project level and then passing the arguments `-d .` works just fine.

![Screen Shot 2020-02-17 at 2 01 38 PM](https://user-images.githubusercontent.com/21271446/74680342-48fd7f00-518e-11ea-9d24-3dc6f7497f44.png)

**Comment by iAmBipinPaul** [comment]
@KZeronimo Hi , I thik it will always open at solution level.
In my case , I have both as false (solution level as well project level) , it works fine as expected.

Opens in current directory as it is in the case of other terminal (cmd).
