### ISSUE TITLE
Option to pick PowerShell Core

### ISSUE THREAD

**Issue by xt0rted** [madskristensen/OpenCommandLine#79]
Launching PowerShell now shows a notice about trying PowerShell Core (which I've switched to), it'd be useful if this was an option instead of having to set it up as a custom console.

```terminal
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

Loading personal and system profiles took 979ms.
C:\dev>
```

**Comment by michha** [comment]
As I looked for it today, this seems to be already in the code (see #74) but last Visual Studio Gallery update is from October 2018.
@madskristensen could you please push a new version to the gallery?

**Comment by madskristensen** [comment]
@michha @xt0rted getting ready to release new version in 5 minutes

**Comment by madskristensen** [comment]
New version released

**Comment by IanKemp** [comment]
> 
> 
> New version released

Good to know you're still alive Mads, and thanks for the release.
