### ISSUE TITLE
Not working with VS2022? EnvDTE not found

### ISSUE THREAD

**Issue by conficient** [madskristensen/OpenCommandLine#94]
Trying out VS2022 Enterprise (v17 Preview). Installing any extension seems to fail, including this one:
```
SetSite failed for package [OpenCommandLinePackage]Source: 'OpenCommandLine'; Description: Could not load file or assembly 'EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```
Full log file: [ActivityLog.zip](https://github.com/madskristensen/OpenCommandLine/files/6686254/ActivityLog.zip)

** What I've tried so far**

- Remove and reinstall the extension
- Run Repair on VS2022 installation
- Checked folder `C:\Program Files\Common Files\microsoft shared\MSEnv` - there is no `PublicAssemblies` folder in here, as there is for `C:\Program Files (x86)\Common Files\Microsoft Shared\MSEnv\PublicAssemblies`

Platform: Windows 10 Pro v2004 build 19041.1052

**Comment by conficient** [comment]
Having found nothing on this issue anywhere, I decided to just copy the folders from the x86 `MSEnv` folder into the 64-bit `MSEnv` folder and that seems to have fixed it.

Could be a general issue with VS2022 when installed side-by-side with 32-bit versions?

**Comment by conficient** [comment]
This technique worked for a while but is now breaking again intermittently.

**Comment by madskristensen** [comment]
I think they found the bug was with VS 2022 Preview 1 and that a fix is coming in the next preview release

**Comment by conficient** [comment]
Thanks for the update @madskristensen - I'll leave this open and check again when preview 2 lands

**Comment by conficient** [comment]
A separate report on [DeveloperCommunity feedback](https://developercommunity.visualstudio.com/t/Could-not-load-file-or-assembly-EnvDTE/1463536?space=8&q=%5BVisual+Studio+2022+version+17.0%5D+envdte&stateGroup=active&ftype=problem&sort=votes)

**Comment by conficient** [comment]
Just seen [this MS response](https://developercommunity.visualstudio.com/t/dte-events-not-working-in-vs2022/1455126#T-N1471948) on the developer community site related to EnvDTE:

> This version of Visual Studio requires recompilation against the new PIA layer which contains numerous 64 bit specific fixes. It is not supported to compile against the old extensibility dlls (like EnvDTE) and run in this version of VS. The error you are seeing is indicating that is what you have done, the signature on the delegate has had its second parameter changed from native uint to native int (this is a Roslyn compiler change, not something we did explicitly), which means compiling against the old PIAs will expect the second param of the ctor to be native uint, but it is not that any longer.
> 
> Ryan Molden
> Software Engineer
> Microsoft Visual Studio Performance and Reliability Team
> 
Does this mean the code in [VsHelpers.cs](https://github.com/madskristensen/OpenCommandLine/blob/master/src/OpenCommandLine/Helpers/VsHelpers.cs) is wrong for VS2022 ?

**Comment by conficient** [comment]
Just trying out VS2022 preview 2.0 and it seems to be fixed now - all Extensions firing okay.

**Comment by conficient** [comment]
Update: it's not fixed but I won't re-open the issue as I believe it's VS2022

**Comment by TimKras** [comment]
There was a siilar problem with this extension, which is now fixed: https://github.com/ErikEJ/EFCorePowerTools/issues/1046

**Comment by conficient** [comment]
I'm trialling a new extensions in VS 2022 preview 4 .. so far no errors
