### ISSUE TITLE
Does not work with Visual Studio 2022 (Preview) unless VS is started without code

### ISSUE THREAD

**Issue by coosmiin** [madskristensen/OpenCommandLine#95]
The extension configuration fails to load.
![image](https://user-images.githubusercontent.com/3222985/132807624-68ad1c0a-fe31-4a70-aa88-671ff3530659.png)

We can see some errors in the log file: 
[ActivityLog.zip](https://github.com/madskristensen/OpenCommandLine/files/7141660/ActivityLog.zip)

Everything is fine if VS is started without code and then a solution is loaded. Looks like a race condition.

**Comment by madskristensen** [comment]
Grab the new separate extension for VS 2022. It now works correctly.
